FROM alpine:3.14
LABEL maintainer="Sravan"
USER root
RUN apk add --update --no-cache \
jq \
curl \
bash \
zip \
openjdk17 \
tzdata \
aws-cli \
docker-cli \
less \
rsync \
maven \
git

RUN curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.1.3023-linux.zip -o /tmp/sonar-scanner.zip && \
unzip /tmp/sonar-scanner.zip -d /opt && \
rm /tmp/sonar-scanner.zip  && \
mv /opt/sonar-scanner-4.8.1.3023-linux /opt/sonar-scanner 

RUN sed -i 's/use_embedded_jre=true/use_embedded_jre=false/g' /opt/sonar-scanner/bin/sonar-scanner
ENV TZ="Asia/Kolkata"
CMD ["bin/bash"]