FROM alpine:3.14
LABEL maintainer="Sravan"
USER root
RUN apk add --update --nocache \
jq \
curl \
bash \
zip \
openjdk11 \
tzdata \
aws-cli \
docker-cli \
less \
rsync \
maven \
git

RUN curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.1.3023-linux.zip -o /tmp/sonar-scanner.zip && \
unzip /tmp/sonar-scanner.zip -d /opt && \
rm /tmp/sonar-scanner.zip  && \
mv /opt/sonar-scanner-cli-4.8.1.3023-linux /opt/sonar-scanner 

ENV TZ="Asia/Kolkata"
CMD ["bin/bash"]